In [14]:
import numpy as np
a = np.array([[1,2,3],[1,2,7]])
b = np.mean(a, axis=0)
c = np.array([1, 3, 5])
d = a*c
e = np.array([100, 300, 500])
f = d+e
print(a.shape)
print(c.shape)
print(d)
print(f)

(2, 3)
(3,)
[[ 1  6 15]
 [ 1  6 35]]
[[101 306 515]
 [101 306 535]]


In [12]:
a=[None]*5
a[4]=1
print(a)

[None, None, None, None, 1]
