In [4]:
import numpy as np
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
import numpy as np
a = [1,2,3]
b = [4,5,6]
c = np.matmul(a,b)
print(c)
d = np.multiply(a,b)
print(d)

32
[ 4 10 18]


In [8]:
import numpy as np
a =  np.array([[1,2,3], [0,0,0]]) 
b = np.array([4,5,6])
c = np.matmul(a,b)
print(c)
d = np.multiply(b,a)
e = b*a
print(d)
print(e)

[32  0]
[[ 4 10 18]
 [ 0  0  0]]
[[ 4 10 18]
 [ 0  0  0]]


In [1]:
for i in range(5, -1, -1):
    print(i)

5
4
3
2
1
0
