In [26]:
import numpy as np
a = np.array([[0,0,0],[1,1,1]])
print(a)
a[0,:] = 5
print(a)

[[0 0 0]
 [1 1 1]]
[[5 5 5]
 [1 1 1]]


In [17]:
import numpy as np
mask = np.random.choice(12, 5, replace=False)
print(mask)

[ 2  4  0 10  8]


In [22]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]
