In [6]:
import numpy as np
a = np.array([[0., 1., 2.], [7., 5., 3.], [2., 3., 4.], [3., 4., 5.]])
b = np.array([[0,1,2], [2, 3, 4]])
c = [] #np.zeros((4,1))
d = []
c = a[0,:] - b[1,:]
d = np.square(c)    
e = np.sum(d)
f = np.sqrt(e)    
print(c)
print(d)
print(e)
print(f)
ids = np.argsort(a[1])
print(ids)
print(ids[:3])

[-2. -2. -2.]
[4. 4. 4.]
12.0
3.4641016151377544
[2 1 0]
[2 1 0]


In [10]:
import numpy as np
a = np.array([0, 3, 2, 1,2, 1, 2, 1, 2, 2, 0, 0, 1, 3, 4])
unique, counts = np.unique(a, return_counts=True)
b = dict(zip(unique, counts))
id = np.argmax(counts)
print(counts)
print(b)
print(b[0])
print(b[1])
print(id)

[3 4 5 2 1]
{0: 3, 1: 4, 2: 5, 3: 2, 4: 1}
3
4
2


In [20]:
import numpy as np
a = np.array([[1, 2, 3, 7], [1, 2, 3, 5], [1, 2, 3, 1]])
b = np.array([[1, 2, 3, 7], [1, 2, 3, 5]])
c = a-b

print(b)
print(c)


ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [28]:
import numpy as np
a = np.array([[1, 2, 3, 7], [1, 2, 3, 5], [1, 2, 3, 1]])

for i in range (3):
    print(a[:2])

[[1 2 3 7]
 [1 2 3 5]]
[[1 2 3 7]
 [1 2 3 5]]
[[1 2 3 7]
 [1 2 3 5]]


In [21]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array_split(a,3)
c = np.delete(b, 1, 0)

print(b)
print(b[0][2])
print(c)
c = np.reshape(c,(-1,1))
print(c)


[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
3
[array([1, 2, 3, 4]) array([ 8,  9, 10])]
[[array([1, 2, 3, 4])]
 [array([ 8,  9, 10])]]


In [18]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
kt = {}
kt = {'one': a, 'two': 2, 'three': 3}
i = 4
kt[i] = 5
print(kt)

{'one': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 'two': 2, 'three': 3, 4: 5}


In [16]:
fruitdict = {}
for i in ('apple', 'banana', 'carrot'):
    fruitdict[i] = locals()[i]

KeyError: 'apple'