In [19]:
import numpy as np
a = np.array([[0,4,5],[1,6,7],[8,1,9]])
b = np.array([[0],[1],[2]])
print(a)
print(b)
c = a-b
print(c)

[[0 4 5]
 [1 6 7]
 [8 1 9]]
[[0]
 [1]
 [2]]
[[ 0  4  5]
 [ 0  5  6]
 [ 6 -1  7]]


In [17]:
a = [4, -3, 5, -7, -6, -8]
max = np.maximum(0,a)
print(a)
print(max)


[4, -3, 5, -7, -6, -8]
[4 0 5 0 0 0]
